env:
  global:
    - PACKAGE="gruvbox"
    - SUBLIME_TEXT_VERSION="3"
    - UNITTESTING_TAG="master"
    - COLOR_SCHEME_UNIT_TAG="master"

matrix:
  include:
    - language: node_js
      node_js: stable
      before_script:
        - npm install

      cache:
        directories: node_modules

      script:
        - npm run validate

    - language: python
      python: 3.3

      cache:
        directories: node_modules

      before_install:
        - nvm install node
        - nvm use node
        - npm install
        - npx gulp build_all
        - curl -OL https://raw.githubusercontent.com/Briles/UnitTesting/master/sbin/travis.sh
        # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
        - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
          fi

      install:
        - sh travis.sh bootstrap
        # - sh travis.sh install_package_control
        - sh travis.sh install_color_scheme_unit
        # install LESS package
        - sh scripts/install_subl_package.sh "LESS" "https://github.com/danro/LESS-sublime"
        # install SCSS package
        - sh scripts/install_subl_package.sh "Sass" "https://github.com/braver/SublimeSass"
        # install Jade package
        - sh scripts/install_subl_package.sh "Jade" "https://github.com/davidrios/jade-tmbundle" "master"
        # install Pug package
        - sh scripts/install_subl_package.sh "Pug" "https://github.com/davidrios/pug-tmbundle" "master"
        # install TypeScript package
        - sh scripts/install_subl_package.sh "TypeScript" "https://github.com/Microsoft/TypeScript-Sublime-Plugin"
        # install Vue Syntax Highlight package
        - sh scripts/install_subl_package.sh "Vue Syntax Highlight" "https://github.com/vuejs/vue-syntax-highlight" "new"
        # install Better Coffeescript package
        - sh scripts/install_subl_package.sh "Better Coffeescript" "https://github.com/aponxi/sublime-better-coffeescript" "master"
        # install Laravel Blade package
        - sh scripts/install_subl_package.sh "Laravel Blade" "https://github.com/Medalink/laravel-blade"
        # install Babel package
        - sh scripts/install_subl_package.sh "Babel" "https://github.com/babel/babel-sublime" "master"

      script:
        - sh travis.sh run_color_scheme_tests --coverage

os:
  - linux

sudo: false

branches:
  only:
    - develop
